server:
    port: 80
    compression:
        min-response-size: 512
        enabled: true
        mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg,application/javascript
    undertow:
        io-threads: 4
        worker-threads: 10
        buffer-size: 16384
        accesslog:
            enabled: true
            dir: /home/jcala/xmarket/log/server_log
            pattern: combined
#    ssl:
#        key-store: classpath:sample.jks
#        key-store-password: secret
#        key-password: password
#        enabled: true
    context-path: /api/v1
logging:
    config: classpath:logback-spring.xml
    path: /home/jcala/xmarket/log/spring_log
spring:
    http:
        encoding.charset: UTF-8
        encoding.force: false
        multipart:
          max-file-size: 3MB
          max-request-size: 10MB
    data:
        mongodb:
            database: xmarket
            host: 127.0.0.1
            port: 27017
xmarket:
    pic_home: G:\home\jcala\xmarket\pic
    jwt:
        key: shaku$#&!><?SD*o349()?/,<>+
        life: 7200000
